# Example:
rules:
  - name: core-public-api
    when_changed:
      - "engine/core/include/**"
      - "engine/core/public/**"
    must_also_change:
      - "sub-agent/core/interfaces.md"
      - "sub-agent/core/changelog.md"

  - name: render-public-api
    when_changed:
      - "engine/render/include/**"
      - "engine/render/public/**"
      - "engine/render/rhi/**"
    must_also_change:
      - "sub-agent/render/interfaces.md"
      - "sub-agent/render/changelog.md"

  - name: editor-rpc-contract
    when_changed:
      - "engine/editor/**"
      - "entry/editor/**"
      - "schemas/editor_rpc/**"
    must_also_change:
      - "agent/integration/editor-rpc.md"
