rules:
  - name: core-public-api
    when_changed:
      - "engine/core/include/**"
      - "engine/core/public/**"
      - "engine/core/source/core/**"
    must_also_change:
      - "agent/sub-agent/core/interfaces.md"
      - "agent/sub-agent/core/changelog.md"

  - name: graphics-public-api
    when_changed:
      - "engine/graphics/include/**"
      - "engine/graphics/public/**"
      - "engine/graphics/source/graphics/**"
    must_also_change:
      - "agent/sub-agent/graphics/interfaces.md"
      - "agent/sub-agent/graphics/changelog.md"

  - name: editor-rpc-contract
    when_changed:
      - "engine/editor/**"
      - "entry/editor/**"
      - "schemas/editor_rpc/**"
    must_also_change:
      - "agent/integration/editor-rpc-mode.md"
