# cmake/AprilModule.cmake

include(cmake/tools.cmake)

function(april_define_module MODULE_ROOT_DIR DIR_NAME)
    set(MODULE_PATH "${MODULE_ROOT_DIR}/${DIR_NAME}")
    set(MANIFEST_FILE "${MODULE_PATH}/manifest.txt")

    if(NOT EXISTS "${MANIFEST_FILE}")
        return()
    endif()

    set(MODULE_NAME "April_${DIR_NAME}")
    april_parse_manifest("${MANIFEST_FILE}" MODULE_VERSION MODULE_DEPS)

    message(STATUS "[AutoLoader] Configuring: ${MODULE_NAME} (v${MODULE_VERSION})")

    file(GLOB_RECURSE SRC_FILES CONFIGURE_DEPENDS
        "${MODULE_PATH}/source/*.cpp"
        "${MODULE_PATH}/source/*.ixx"
    )
    file(GLOB_RECURSE HDR_FILES CONFIGURE_DEPENDS
        "${MODULE_PATH}/source/*.hpp"
    )

    if(NOT SRC_FILES)
        set(DUMMY_FILE "${CMAKE_BINARY_DIR}/modules/${DIR_NAME}/April_Auto_Dummy.cpp")

        if(NOT EXISTS "${DUMMY_FILE}")
            file(WRITE "${DUMMY_FILE}" "// Auto-generated by April Engine Build System\n// This file exists because module '${MODULE_NAME}' has no source files.\n")
        endif()

        list(APPEND SRC_FILES "${DUMMY_FILE}")

        message(STATUS "  -> [Info] No source files found. Generated dummy file to allow STATIC library creation.")
    endif()

    add_library(${MODULE_NAME} STATIC ${SRC_FILES} ${HDR_FILES})

    set_target_properties(${MODULE_NAME} PROPERTIES
        VERSION ${MODULE_VERSION}
        APRIL_DEPS_LIST "${MODULE_DEPS}"
    )

    string(TOUPPER ${MODULE_NAME} UPPER_NAME)
    target_compile_definitions(${MODULE_NAME} PRIVATE ${UPPER_NAME}_BUILD)

    target_compile_features(${MODULE_NAME} PUBLIC cxx_std_23)

    target_include_directories(${MODULE_NAME}
        PUBLIC
            $<BUILD_INTERFACE:${MODULE_PATH}/source>
            ${MODULE_PATH}/source/${DIR_NAME}
            $<INSTALL_INTERFACE:include>
        PRIVATE
            ${MODULE_PATH}/source/${DIR_NAME}
    )

    april_helper_handle_library(${MODULE_NAME} ${MODULE_PATH} ${DIR_NAME})
    april_helper_sync_shader(${DIR_NAME} "${MODULE_PATH}")

endfunction()

function(april_link_module MODULE_ROOT_DIR DIR_NAME)
    set(MODULE_NAME "April_${DIR_NAME}")

    if(NOT TARGET ${MODULE_NAME})
        return()
    endif()

    get_target_property(MODULE_DEPS ${MODULE_NAME} APRIL_DEPS_LIST)

    foreach(DEP ${MODULE_DEPS})
        string(STRIP "${DEP}" DEP)
        if(DEP)
            message(STATUS "[Link Debug] Linking '${MODULE_NAME}' with '${DEP}'")
            target_link_libraries(${MODULE_NAME} PUBLIC ${DEP})
        endif()
    endforeach()

endfunction()


function(april_scan_and_load_modules ROOT_PATH)
    file(GLOB CHILDREN RELATIVE "${ROOT_PATH}" "${ROOT_PATH}/*")

    # Pass 1: Define
    foreach(CHILD ${CHILDREN})
        if(IS_DIRECTORY "${ROOT_PATH}/${CHILD}")
            april_define_module("${ROOT_PATH}" "${CHILD}")
        endif()
    endforeach()

    # Pass 2: Link
    foreach(CHILD ${CHILDREN})
        if(IS_DIRECTORY "${ROOT_PATH}/${CHILD}")
            april_link_module("${ROOT_PATH}" "${CHILD}")
        endif()
    endforeach()
endfunction()
